version: "3.8"
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
      driver: default
services:
  nats-server:
    networks:
      - main
    image: docker.io/linuxforhealth/jetstream:v0.0.19
    volumes:
      - ./local-certs:/certs
    command: server --tls \
      --tlscert=/certs/nats-server.crt \
      --tlskey=/certs/nats-server.key \
      --tlscacert=/certs/rootCA.crt
    ports:
      - "4222:4222"
  zookeeper:
    networks:
      - main
    image: docker.io/linuxforhealth/zookeeper-alpine:3.6.2
    expose:
      - "2181"
  kafka:
    networks:
      - main
    image: docker.io/linuxforhealth/kafka-alpine:2.5.0
    restart: "always"
    expose:
      - "9092"
      - "9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
