version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: TRACE
    formatter: simple
    stream: ext://sys.stdout
root:
  level: WARN
  handlers: [console]
loggers:
  connect:
    level: TRACE
  uvicorn:
    level: INFO
