# builds a multi-platform pyConnect image
name: pyConnect Multi-Platform Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: linuxforhealth/connect:latest
